stages:
  - test
test:
  stage: test
  script:
    - echo "Compile project"
    - export PATH=${GRADLE_HOME}/bin:${ANDROID_SDK_ROOT}/tools/bin:${PATH}
    - gradle clean
    - gradle build
    - gradle test
    - gradle compileDebugSources
    - gradle compileDebugAndroidTestSources
    - gradle assembleAndroidTest
    - echo "Upload compiled binaries"
    - scp app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk pi@10.8.0.27:/home/pi/tests/morsetrainer/app-debug-androidTest.apk
    - scp app/build/outputs/apk/debug/app-debug.apk pi@10.8.0.27:/home/pi/tests/morsetrainer/app-debug.apk
    - echo "Install scripts to test device"
    - ssh pi@10.8.0.27 "adb -s ZY223NB8FP uninstall com.maxistar.morsetrainer.test"
    - ssh pi@10.8.0.27 "adb -s ZY223NB8FP uninstall com.maxistar.morsetrainer"
    - ssh pi@10.8.0.27 "adb -s ZY223NB8FP install -r -t /home/pi/tests/morsetrainer/app-debug-androidTest.apk"
    - ssh pi@10.8.0.27 "adb -s ZY223NB8FP install -r -t /home/pi/tests/morsetrainer/app-debug.apk"
    - echo "Run tests"
    - ssh pi@10.8.0.27 "adb -s ZY223NB8FP shell am instrument -w -e debug false com.maxistar.morsetrainer.test/androidx.test.runner.AndroidJUnitRunner"
